language: c
sudo: false
after_success: bash <(curl -s https://codecov.io/bash)
install:
  - if test "$TRAVIS_OS_NAME" = linux; then sudo apt-get install libmbedtls-dev; else brew install jq mbedtls; fi
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script: make test test++
matrix:
  include:
    - os: osx
      compiler: clang
      script: make mg_prefix vc98 vc2017 ex
      sudo: required
      services:
        - docker
