name: build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install libmbedtls-dev
    - name: make
      run: make test test++
    - name: openssl
      run: make test SSL=OPENSSL
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install jq mbedtls openssl
    - name: make
      run: make test++ upload-coverage
    - name: openssl
      run: make test SSL=OPENSSL
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make mg_prefix vc98 vc2017 ex

